name: tests

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

permissions:
    contents: read

env:
    ENV_NAME: testing
    BASE_URL: 127.0.0.1:8000
    DB_URL: sqlite:///./db.sqlite3
    INTERVAL: 3600

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                python-version: ["3.9", "3.10"]

        steps:
            - uses: actions/checkout@v2

            - name: Set up Python ${{ matrix.python-version }}
            uses: actions/setup-python@v2
            with:
                python-version:  ${{ matrix.python-version }}

            - name: Install dependencies
            run: |
                python -m pip install --upgrade pip
                python -m pip install -r requirements.txt

            - name: Test api
            run: python -m unittest discover