name: tests

on:
  push:
    branches: ["main"]
  pull_request:
      branches: ["main"]

permissions:
  contents: read

env:
  ENV_NAME: testing
  BASE_URL: 127.0.0.1:8000
  DB_URL: sqlite:///./db.sqlite3
  INTERVAL: 3600

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Sync dependencies
        run: uv sync

      - name: Lint and Format checks
        run: |
          uv run ruff check
          uv run ruff format --check

      - name: Type checking
        run: uv run mypy api

      - name: Test api
        run: uv run pytest